spring.application.name=cloud-task-manager
# Aiven Cloud MySQL Database Connection
spring.datasource.url=jdbc:mysql://mysql-4d03e99-vivekchauhan11mg-624.j.aivencloud.com:23144/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=DUMMY_PASSWORD

# Hibernate Settings (Ye automatic tables create kar dega)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true